CREATE TABLE IF NOT EXISTS t_players
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_name varchar(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_name_idx ON t_players (c_name);

CREATE TABLE IF NOT EXISTS t_matches
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_first_player_id  BIGINT,
    c_second_player_id BIGINT,
    c_winner_id        BIGINT,
    FOREIGN KEY (c_first_player_id) REFERENCES t_players (id),
    FOREIGN KEY (c_second_player_id) REFERENCES t_players (id),
    FOREIGN KEY (c_winner_id) REFERENCES t_players (id)
);